### ISSUE TITLE
Sorry I’m a noob with GitHub

### ISSUE THREAD

**Issue by Jonathan2945** [RuvenBeck/Legendary-Streamer#2]
How do I list playlist, is it playlist link Per-line  or what ? 

How do I list the combo, username-password or username:password?    Per-line

How do I list the proxies? can you give me a example of what is should look like.   

Once everything is inputted what’s is the command I run to start the program?  Thanks in advanced

**Comment by RuvenBeck** [comment]
Thank you for this issue, im gonna put this also in the readme.

So for the playlist you have to put the url from your browser into like this: https://open.spotify.com/playlist/7CyjeRLDcAWLuXTN7Dwj2z

For the accounts: username:password

Try to use proxies without user:password 

To run it open the cmd in the folder and put in: python streamer.pay

**Comment by Jonathan2945** [comment]
TypeError:[image](https://github.com/RuvenBeck/Legendary-Streamer/assets/137711746/7f4bb48f-e9cc-4d8e-8f16-ab2c3942e941) got an unexpected keyword argument "executable_path'

**Comment by Jonathan2945** [comment]
Error message ![image](https://github.com/RuvenBeck/Legendary-Streamer/assets/137711746/6129a54e-6b1a-47c7-887a-d2a262d7b211)

**Comment by RuvenBeck** [comment]
Should be working now

**Comment by Jonathan2945** [comment]
(Above)
![image](https://github.com/RuvenBeck/Legendary-Streamer/assets/137711746/533e7f93-295d-4c51-a8e5-500b566ccf8e)



Not sure what's going on here opens chrome then won't load then closes chrome give this 

(Below)
![image](https://github.com/RuvenBeck/Legendary-Streamer/assets/137711746/c91e0df0-4cf5-42ee-abc3-307bee7acf29)

**Comment by RuvenBeck** [comment]
The problem is that your chrome spotify pages isnt loading and then the timer from the condition of the wait expires and then closes because of this error. Dont know what the error in your particular code is.
